### ISSUE TITLE
Look into Time.timeScale as new way to control dance speed.

### ISSUE THREAD

**Issue by natis1** [natis1/infinitegrimm#31]
Its value affects the speed of ALL animations, inc the knight and grimm. Maybe worth looking into to make the fight more fluid? probably will just ruin muscle memory.

**Comment by 5FiftySix6** [comment]
yes

**Comment by natis1** [comment]
I did this already. Thanks for reminding me to close all my old issues on this site since I don't really use it anymore except as a mirror for my larger projects.
